### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [mce777/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by mce777** [comment]
Added this tag to application.html.erb:
<meta name="viewport" content="width=device-width, initial-scale=1">

tested in the device simulator in chrome and on my actual mobile device. Looking better.

**Comment by kenmazaika** [comment]
:+1: thumbs up!  Looks solid! :)
